# Generated by Django 5.0.6 on 2026-07-20 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_consultation', models.CharField(choices=[('GENERALISTE', 'Généraliste'), ('SPECIALISTE', 'Spécialiste'), ('URGENCE', 'Urgence')], max_length=20)),
                ('date', models.DateField()),
                ('prix', models.DecimalField(decimal_places=0, max_digits=8)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='patients.patient')),
            ],
        ),
    ]
