# Generated by Django 5.0.6 on 2026-07-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
